# Generated by Django 5.1.4 on 2025-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
    ]
